apiVersion: v1
kind: Secret
metadata:
  name: inframind-secrets
  namespace: inframind
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:SecureProdPass123!@inframind-db.us-east-1.rds.amazonaws.com:5432/inframind"
  REDIS_URL: "redis://inframind-redis.us-east-1.cache.amazonaws.com:6379/0"
  OPENAI_API_KEY: "sk-proj-placeholder-secret-key-change-me"
